# Generated by Django 3.1 on 2025-04-15 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='review_en',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='review_ru',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject_en',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject_ru',
        ),
    ]
